### ISSUE TITLE
Travis Setup automated testing

### ISSUE THREAD

**Issue by marcj** [propelorm/Propel3#23]
Currently pull-requests/branches are not tested automatically in travis.

**Comment by cristianoc72** [comment]
A coupleof questions:
1.  which Mysql and Postgresql versions we should test against? Travis default ones can be enough?
2.  is Code climate (with code coverage) triggered by CircleCi scripts?

**Comment by marcj** [comment]
1. I guess default is enough, which should be nearly the newest.

2. Code climate is not yet integrated. Its triggered by Github hooks. The coverage is custom made (as code climate does not support code coverage over multiple builds, but only for one) in https://github.com/propelorm/Propel3/blob/master/.travis.yml#L135

**Comment by cristianoc72** [comment]
👍
