### ISSUE TITLE
Propel\Generator\Command\Helper\DialogHelper error

### ISSUE THREAD

**Issue by MaksSlesarenko** [propelorm/Propel3#54]
Propel\Generator\Command\Helper\DialogHelper depends on Symfony\Component\Console\Helper\DialogHelper which was replaced in Symfony3 by Symfony\Component\Console\Helper\QuestionHelper

bin/propel init
PHP Fatal error:  Class 'Symfony\Component\Console\Helper\DialogHelper' not found in /application/Propel3/src/Propel/Generator/Command/Helper/DialogHelper.php on line 7

**Comment by marcj** [comment]
Well, never worked with DialogHelper. My very vague guess is it is from the init command maybe, @mpscholten?

**Comment by gossi** [comment]
It's mostly used, when a propel cli command asks for input ;)

**Comment by cristianoc72** [comment]
Imho we should bump to Symfony components v 3 (maybe choosing a long time support version).
If it's ok, I can fix it.

**Comment by marcj** [comment]
Yes :)
