### ISSUE TITLE
Related objects persistance

### ISSUE THREAD

**Issue by cristianoc72** [propelorm/Propel3#56]
Related objects of a given entity are not sincronized with the database (this issue is reproduced along `Propel\Tests\Generator\Builder\Om\GeneratedObjectRelTest` test case). 

Get a look at the following code:
```php
$author = new Author();
$author->setName('Oscar Wilde');
$author->save();

$book1 = new Book();
$book1->setTitle('The picture of Dorian Gray');
$book1->setAuthor($author);

$book2 =new Book();
$book2->setTitle('The importance of being Ernest');
$author->addBook($book2);
$author->save();
```
Everything is ok: 1 author related with 2 books, both  in memory and in db. If I add a book:
```php
$book3 = new Book();
$book3->setTitle('The Duchess of Padua');
$book3->setAuthor($author);
$author->save();
```
Everything is ok: 1 author related with 3 books, both  in memory and in db.
But if I **remove** a book:
```php
$author->removeBook($book1);
$author->save();
```
Now I have: 1 author and 2 books in memory and 1 Author and 3 books in the db. 
If I add another book, then I find 4 books in the db.

Possible solutions:

1. when removing related objects, perform a query to also delete the entity from the database. This piece of code should be written in `removeXXX` method.
2. implement a way to mark the entity as 'deleted' and let the persister do the deletion work, via `presistDependencies` method
3. implement a preSave hook which cleanup the database before persistence
4. (suggestions?)

Suggestions are wellcome!

**Comment by marcj** [comment]
Shouldn't you have still book3 in memory? `removeBook` should only break the relation, not delete the book3 entity from the database in my opinion.

**Comment by cristianoc72** [comment]
Ok! Anyway, `removeBook` should update the database, because if I break the relation, the removed object is no more a dependency and it's not persisted with the `Author` entity, isn't it?

**Comment by marcj** [comment]
Yes, it should update the database. It actually is still related, as the db state indicates still that it is related. Once it goes through the change detection it needs to check whether it sets the foreign key from Book to Author accordingly to null.

**Comment by marcj** [comment]
Yes it should set the foreign key to null. But I thought this works already😱

**Comment by cristianoc72** [comment]
Found!
The in-memory process works correctly (as @marcj told before) it seems that the modification isn't persisted. Anyway, I misunderstood a couple of test cases :grimacing: .....
I'm closing this issue.
Thank you!
