### ISSUE TITLE
Why one repository for each major version?

### ISSUE THREAD

**Issue by odahcam** [propelorm/Propel3#66]
I mean, just tagging the versions wasn't enough? 🤔

**Comment by marcj** [comment]
Because its this way more convenient to us.

**Comment by odahcam** [comment]
All right, it's a very cool lib btw. Propel3 looks like [illuminate/database](1) + [doctrine/doctrine2](2) perfect union, can't wait for the stable release and find other libs using it.

[1]: https://github.com/illuminate/database
[2]: https://github.com/doctrine/doctrine2
