### ISSUE TITLE
is the project still maintained?

### ISSUE THREAD

**Issue by Snake231088** [propelorm/Propel3#70]
Please don't stop to work on Propel3!
Now i'm on Propel2 and i waiting first release of Propel3

**Comment by cristianoc72** [comment]
Don't worry, we're on it!
@gossi is working hard on #61 , which is a VERY big refactor. It'll improve the generation part and the mantainability of the whole project.
By now, I'm continuing to fix the test suite, but we can't commit anything before #61 will be merged.
Thank you for your appreciation!

**Comment by Snake231088** [comment]
Thx!!!
