### ISSUE TITLE
External-schema support and packages

### ISSUE THREAD

**Issue by cristianoc72** [propelorm/Propel3#84]
While working on #83 I implemented some loaders, to load schema files in different formats (xml, yaml, json, php).
Now I should work on merging external schemas and different packages.

My questions are:
1) packages were born to simulate a sort of namespaces, when they were not implemented yet in php. Are Propel packages still useful? (I used them at the time of Propel 1.5 :smile: )
2) Since I can have multiple schemas, describing my domain, living in the same project, is `external-schema` still useful? (I never used this feature)

**Comment by gossi** [comment]
Oh yes, please. if your application is modularized, external-schemas is the way to link to "core/other" packages and get relations correct. Because `external-schema` has a bad "include" paths to those external files, that was my initial idea behind refactoring the schema loader 😉
