### ISSUE TITLE
Is Propel dead dead now?

### ISSUE THREAD

**Issue by oojacoboo** [propelorm/Propel3#86]
Would like to hear about the status of Propel.  We manage a large application that actually still runs on Propel 1.  Preparing the codebase for migration to Propel 2 (or so we thought), has been a slow process of eliminating the PEER classes and organizing our query logic.  That said, we're basically to the point now where we have very few PEER calls in our code and most of our query logic put into a custom repository layer.  We could actually pull off the migration now.

While migrating to Propel 2 probably still makes sense for us, even given that there isn't a stable release and it's been abandoned, looking forward, if and when the time comes for us to actually make a move, that decision path is getting fuzzy.

Propel 1 mostly works, but there are some absolutely crazy gotchas that require some even crazier hacks.

Aside from the question on the status.  I'd like to know if there is a migration path, or migration suggestions/instructions to move from Propel 2 to Propel 3.  Does Propel 3 even work?  Is Propel 3 anymore stable than Propel 2?  Cheers!

**Comment by jstrzal** [comment]
Up, should we consider changing ORM?

**Comment by gossi** [comment]
This is where the activity is happening #83

**Comment by oojacoboo** [comment]
@jstrzal it seems so - been nearly a year and a PR hasn't been merged.

**Comment by marcj** [comment]
Yupp, seems so.
