### ISSUE TITLE
Table prefix and packages

### ISSUE THREAD

**Issue by cristianoc72** [propelorm/Propel3#87]
Now that the new object model is almost ready, it's time to decide the fate of  `package` and `table prefix` options.
Should we continue to support them or they can be removed?
@gossi @marcj

**Comment by gossi** [comment]
If I recall the last discussion, we are at the point to drop them. That is, table prefixes were a thing back in the day, when hosters only offered you one database and you want to probably install the same app twice and more databases were expensive. Nowadays deployment of apps changed drastically. It's like spinning up databases on demand =) Drop them, they just cause confusion and recall a thing from the past.

**Comment by gossi** [comment]
I think packages only confused me ;) I also think they predated php 5.3 (namespaces) where packages were used by phpdoc to structure code into folders for documentation purpose? I don't know if I'm correct here, if so drop them, too.

**Comment by marcj** [comment]
I'd drop both

**Comment by cristianoc72** [comment]
Agree. I'm going to drop both.

Il giorno sab 26 gen 2019, 00:32 Marc J. Schmidt <notifications@github.com>
ha scritto:

**Comment by cristianoc72** [comment]
closed via #83
